### PR TITLE
ShowSelectedTracksAction: don't get stuck if there's a loop in the graph

### LINKED ISSUE #222: Show track downward in TrackScheme Hierarchy View leads to crash
# Reproduction

1. Start Fiji
2. Plugins > Mastodon
3. open Mastodon project > open grapher-bug.mastodon (download: https://cloudstore.zih.tu-dresden.de/index.php/s/XgbnqRDgb9jLXLb)
4. Window > New TrackScheme Hierarchy
5. Select a branch
6. View > Show Track Downward > Program crashes

# Expected behaviour:

After step 6. "Show Track Downward", the TrackScheme Hierarchy view should zoom to the sub-tree of the selected branch

# File for testing:

https://cloudstore.zih.tu-dresden.de/index.php/s/XgbnqRDgb9jLXLb

# StackTrace:

grafik

# UI interaction:
GIF 16 12 2022 14-52-26

### PR DESCRIPTION
**Pull request by maarzt**
fixes #222

### CODE REVIEW

File: src/main/java/org/mastodon/views/trackscheme/display/ShowSelectedTracksActions.java [hunk 1]
```diff
@@ -192,20 +192,50 @@ private void addEdgeTargets( final RefSet< TrackSchemeVertex > selected,
...
 
+	/**
+	 * @return the root nodes of the selected nodes, i.e. the nodes that are not
+	 * 	   descendants of other selected nodes. The order of the nodes in the returned
+	 * 	   list is from left to right as in the TrackScheme.
+	 */
 	private RefList< TrackSchemeVertex > filterRootNodes( final RefSet< TrackSchemeVertex > selectedVertices )
 	{
+		// Note: This method finds the root nodes of the nodes in the selectedVertices set.
+		// It does so by iterating over the graph in depth-first order and from left to right.
```
Comment (stefanhahmann) [inline src/main/java/org/mastodon/views/trackscheme/display/ShowSelectedTracksActions.java:203]:
```suggestion
		// It does so by iterating over the graph in depth-first order starting from each root. The root nodes are visited in left to right order according to the TrackScheme.
```

File: src/main/java/org/mastodon/views/trackscheme/display/ShowSelectedTracksActions.java [hunk 2]
```diff
@@ -192,20 +192,50 @@ private void addEdgeTargets( final RefSet< TrackSchemeVertex > selected,
...
+		// Whenever the iteration hits a node that is in the selectedVertices set, it adds
+		// it to the returned list, and then skips all its child nodes. This guarantees that
```
Comment (stefanhahmann) [inline src/main/java/org/mastodon/views/trackscheme/display/ShowSelectedTracksActions.java:205]:
```suggestion
		// the root node from which the current iteration started to the returned list, and then skips all its child nodes. This guarantees that
```

**Review by stefanhahmann — CHANGES_REQUESTED** [review]
The pull request fixes the described bug.

I would recommend to add the 2 new notes to the javadoc. It is a private method, but you added javadoc to it anyway already. The notes are very informative and the javadoc would benefit from it.

In general this method seems to be a very efficient way to get the root nodes of selected nodes (and now even avoiding to get stuck in case of loops).

File: src/main/java/org/mastodon/views/trackscheme/display/ShowSelectedTracksActions.java (hunk 1 above)
Comment (maarzt) [reply src/main/java/org/mastodon/views/trackscheme/display/ShowSelectedTracksActions.java]: I changed to comment as suggested. But now the method itself is a bit different. Could check if the current comment works for the updated code.

File: src/main/java/org/mastodon/views/trackscheme/display/ShowSelectedTracksActions.java (hunk 2 above)
Comment (maarzt) [reply src/main/java/org/mastodon/views/trackscheme/display/ShowSelectedTracksActions.java]: Hm. I got the impression that you misunderstood what the method does. I noticed that the method name was a little confusing. I changed it. How does the updated comment reads for you?

Comment (stefanhahmann) [reply src/main/java/org/mastodon/views/trackscheme/display/ShowSelectedTracksActions.java]: Yes, there was a misunderstanding on my side. Comments and javadoc are good now.

**Review by stefanhahmann — COMMENTED** [review]
A code smell has been detected in the findSelectedSubtreeRoots() method.
Apart from this, the changes are perfect. The tests fit well to the intended purpose.

File: src/main/java/org/mastodon/util/TreeUtils.java [hunk 3]
```diff
@@ -0,0 +1,78 @@
...
+				if ( step.isSecondVisit() )
+					continue;
+
+				final V node = step.node();
+
+				// loop detection
+				if ( !visited.add( node ) )  // The depth first iteration enters a node for the second time. -> there's a loop.
+				{
+					step.truncate(); // Don't visit the child nodes
+					continue; // and skip this node.
```
[the remark this answers is not in the document]
Comment (maarzt) [reply src/main/java/org/mastodon/util/TreeUtils.java]: Ok, I changed to code, to loop detection is now in a separate method. Could you look at it again. See if you understand it?

File: src/main/java/org/mastodon/views/trackscheme/display/ShowSelectedTracksActions.java (hunk 2 above)
Comment (maarzt) [reply src/main/java/org/mastodon/views/trackscheme/display/ShowSelectedTracksActions.java]: I removed the comments. The code is now simpler. It should be understandable.

**Review by maarzt — COMMENTED** [review]
I would say the PR is ready. What do you think?

File: src/main/java/org/mastodon/util/TreeUtils.java [hunk 4]
```diff
@@ -0,0 +1,99 @@
...
+	 */
+	public static < V extends Vertex< ? > > RefList< V > findSelectedSubtreeRoots(
+			final Graph< V, ? > graph,
+			final RefList< V > roots,
+			final RefSet< V > selectedVertices )
+	{
+		final RefList< V > selectedSubtreeRoots = RefCollections.createRefList( graph.vertices() );
+		final RefSet< V > visitedNodes = RefCollections.createRefSet( graph.vertices() );
+
+		for ( final V realRoot : roots )
```
Comment (stefanhahmann) [inline src/main/java/org/mastodon/util/TreeUtils.java:49]: I am a bit confused now about what a `realRoot` is. There is now also a method in this in this class called `findRealRoots`. In this function a `realRoot` seems to be something else than within this method. If I understood this correctly, I would think the variable here should be named `root` instead of `realRoot`.

File: src/main/java/org/mastodon/util/TreeUtils.java [hunk 5]
```diff
@@ -0,0 +1,99 @@
...
+		if ( !step.isFirstVisit() )
+			return true;
+
+		boolean isLoop = !visitedNodes.add( step.node() ); // The depth first iteration enters a node for the second time. -> there's a loop.
+		if ( isLoop )
+			step.truncate(); // Break the loop by not visiting the child nodes.
+
+		return !isLoop;
+	}
+
```
Comment (stefanhahmann) [inline src/main/java/org/mastodon/util/TreeUtils.java:75]:
```suggestion
/**
	 * This method finds the root nodes of trees relating to the
	 * given {@code selectedVertices}.
	 * <p>
	 * Example:
	 * <pre>
	 *   A                B
	 *  / \             /   \
	 * a1  a2          b1    b2
	 *     |          / \   / \
	 *     a3        b3 b4 b5 b6
	 *    / \
	 *   a4 a5
	 * </pre>
	 *
	 * If {@code selectedVertices} contains: {@code {a2, a4, a5, b1, b3, b4, b6}},
	 * then the returned list will be: {@code [B, A]}. The order of the returned
	 * root nodes relates to the backward order of how the root nodes were added
	 * to the {@code graph}.
	 * <p>
	 * If {@code selectedVertices} contains: {@code {a2, a4}},
	 * then the returned list will be: {@code [A]}.
	 */
```

May I suggest this Javadoc comment to be added to this very valuable method? I think, it would be even more valuable with that comment, since it was a bit unclear to me what a "real root" is.

File: src/test/java/org/mastodon/util/TreeUtilsTest.java [hunk 6]
```diff
@@ -0,0 +1,111 @@
...
+
+		// test
+		assertEquals( 1, result.size() );
+		assertEquals( b, result.get( 0 ) );
+	}
+
+	@Test
+	public void testFindRealRoots() {
+		// Example graph:
+		//   a   b
```
Comment (stefanhahmann) [inline src/test/java/org/mastodon/util/TreeUtilsTest.java:75]:
```suggestion
		//   a   b   c
```

I would like to suggest to extend this unit test a bit, as it currently does not cover finding multiple roots at the same time.

**Review by stefanhahmann — CHANGES_REQUESTED** [review]
Thanks for adding findRealRoots() to TreeUtils. I am sure this method can be used elsewhere in the project.

I think the related unit test could be a bit extended. Also this method may deserve some javadoc. I made suggestions for both.

The method findSelectedSubtreeRoots() does not contains the detected code smell anymore and is well reabable.

File: src/main/java/org/mastodon/util/TreeUtils.java
Comment (tinevez) [inline src/main/java/org/mastodon/util/TreeUtils.java:1]: In the `mastodon-graph` lib there is RootFinder:
https://github.com/mastodon-sc/mastodon-graph/blob/master/src/main/java/org/mastodon/graph/algorithm/RootFinder.java
Maybe we could merge these two?

**Review by tinevez — APPROVED** [review]

**Review by tinevez — APPROVED** [review]

**Review by tinevez — APPROVED** [review]

File: src/main/java/org/mastodon/util/TreeUtils.java (hunk 5 above)
Comment (maarzt) [reply src/main/java/org/mastodon/util/TreeUtils.java:75]: The method return a list. So it would be very confusing to comment on the order of the returned list.

File: src/test/java/org/mastodon/util/TreeUtilsTest.java [hunk 7]
```diff
@@ -0,0 +1,111 @@
...
+		//  / \
+		// a2 a3
+
+		ModelGraph graph = new ModelGraph();
+		Spot a = graph.addVertex().init( 0, new double[] { 0, 0, 0 }, 1 );
+		Spot a1 = graph.addVertex().init( 0, new double[] { 0, 0, 0 }, 1 );
+		Spot a2 = graph.addVertex().init( 0, new double[] { 0, 0, 0 }, 1 );
+		Spot a3 = graph.addVertex().init( 0, new double[] { 0, 0, 0 }, 1 );
+		Spot b = graph.addVertex().init( 0, new double[] { 0, 0, 0 }, 1 );
+		graph.addEdge( a, a1 ).init();
```
[the remark this answers is not in the document]
Comment (maarzt) [reply src/test/java/org/mastodon/util/TreeUtilsTest.java:94]: The graph has multiple roots. It's not necessary to add a spot c to the test.

File: src/test/java/org/mastodon/util/TreeUtilsTest.java [hunk 8]
```diff
@@ -0,0 +1,111 @@
...
+		graph.addEdge( a1, a2 ).init();
+		graph.addEdge( a2, a3 ).init();
+
+		assertEquals( Collections.singleton( a ), TreeUtils.findRealRoots( graph, Arrays.asList( a, a1, a2, a3 ) ) );
+		assertEquals( Collections.singleton( a ), TreeUtils.findRealRoots( graph, Collections.singleton( a3 ) ) );
+		assertEquals( Collections.singleton( b ), TreeUtils.findRealRoots( graph, Collections.singleton( b ) ) );
```
[the remark this answers is not in the document]
Comment (maarzt) [reply src/test/java/org/mastodon/util/TreeUtilsTest.java]: There is now a test where the method returns two spots.

File: src/main/java/org/mastodon/util/TreeUtils.java (hunk 5 above)
Comment (stefanhahmann) [reply src/main/java/org/mastodon/util/TreeUtils.java:75]: I agree. Then maybe leave out the sentence re order, e.g. like this:

/**
	 * This method finds the root nodes of trees relating to the
	 * given {@code selectedVertices}.
	 * <p>
	 * Example:
	 * <pre>
	 *   A                B
	 *  / \             /   \
	 * a1  a2          b1    b2
	 *     |          / \   / \
	 *     a3        b3 b4 b5 b6
	 *    / \
	 *   a4 a5
	 * </pre>
	 *
	 * If {@code selectedVertices} contains: {@code {a2, a4, a5, b1, b3, b4, b6}},
	 * then the returned set will contain: {@code [A, B]}.
	 * <p>
	 * If {@code selectedVertices} contains: {@code {a2, a4}},
	 * then the returned set will contain: {@code [A]}.
	 */

Comment (maarzt) [reply src/main/java/org/mastodon/util/TreeUtils.java:75]: I updated the comment and pushed it just now.

File: src/test/java/org/mastodon/util/TreeUtilsTest.java (hunk 6 above)
Comment (stefanhahmann) [reply src/test/java/org/mastodon/util/TreeUtilsTest.java:82]: I agree.

File: src/test/java/org/mastodon/util/TreeUtilsTest.java (hunk 7 above)
[the remark this answers is not in the document]
Comment (stefanhahmann) [reply src/test/java/org/mastodon/util/TreeUtilsTest.java:94]: I agree.

File: src/main/java/org/mastodon/util/TreeUtils.java [hunk 9]
```diff
@@ -0,0 +1,146 @@
...
+	 *   A                B
+	 *  / \             /   \
+	 * a1  a2          b1    b2
+	 *     |          / \   / \
+	 *     a3        b3 b4 b5 b6
+	 *    / \
+	 *   a4 a5
+	 * </pre>
+	 * If {@code node} contains: {@code {a2}},
+	 * then the method returns a set {@code {A}}.
```
Comment (stefanhahmann) [inline src/main/java/org/mastodon/util/TreeUtils.java:92]: I would find the example a bit more explanatory, if it would look like this (and if I have understood the remaining Javadoc correctly):

```suggestion
	 * If {@code nodes} contains: {@code {a2}, {a5}, {b6}},
	 * then the method returns a set {@code {A}, {B}}.
```

File: src/test/java/org/mastodon/util/TreeUtilsTest.java [hunk 10]
```diff
@@ -0,0 +1,145 @@
...
+		roots.add( a );
+
+		RefSet< Spot > selectedSpots = RefCollections.createRefSet( graph.vertices() );
+		selectedSpots.add( b );
+
+		// process
+		RefList< Spot > result = TreeUtils.findSelectedSubtreeRoots( graph, roots, selectedSpots );
+
+		// test
+		assertEquals( Arrays.asList( b ), result );
```
Comment (stefanhahmann) [inline src/test/java/org/mastodon/util/TreeUtilsTest.java:76]: Just a minor thing:

```suggestion
		assertEquals( Collections.singletonList(b), result );
```

File: src/test/java/org/mastodon/util/TreeUtilsTest.java [hunk 11]
```diff
@@ -0,0 +1,145 @@
...
+		graph.addEdge( a2, a3 ).init();
+
+		assertEquals( Collections.singleton( a ), TreeUtils.findRootsOfTheGivenNodes( graph, Arrays.asList( a, a1, a2, a3 ) ) );
+		assertEquals( Collections.singleton( a ), TreeUtils.findRootsOfTheGivenNodes( graph, Collections.singleton( a3 ) ) );
+		assertEquals( Collections.singleton( b ), TreeUtils.findRootsOfTheGivenNodes( graph, Collections.singleton( b ) ) );
+		assertEquals( createSet( a, b ), TreeUtils.findRootsOfTheGivenNodes( graph, Arrays.asList( a2, b ) ) );
+	}
+
+	@Test
+	public void testFindRealRoots_dontGetStuckInLoops() {
```
Comment (stefanhahmann) [inline src/test/java/org/mastodon/util/TreeUtilsTest.java:105]: The name of this test still reflects the old method name. Do you want to keep this name anyway?

File: src/test/java/org/mastodon/util/TreeUtilsTest.java [hunk 12]
```diff
@@ -0,0 +1,145 @@
...
+		graph.addEdge( b, c );
+		graph.addEdge( c, b ); // loop between b and c
+		// process
+		RefSet< Spot > result = TreeUtils.findRootsOfTheGivenNodes( graph, Collections.singleton( c ) );
+		// test
+		assertEquals( Collections.singleton( a ), result );
+	}
+
+	@Test
+	public void testFindRealRoots_noTree() {
```
Comment (stefanhahmann) [inline src/test/java/org/mastodon/util/TreeUtilsTest.java:121]: The name of this test still reflects the old method name. Do you want to keep this name anyway?

File: src/test/java/org/mastodon/util/TreeUtilsTest.java [hunk 13]
```diff
@@ -0,0 +1,145 @@
...
+
+		// process
+		RefList< Spot > result = TreeUtils.findSelectedSubtreeRoots( graph, roots, selectedSpots );
+
+		// test
+		assertEquals( Arrays.asList( b ), result );
+	}
+
+	@Test
+	public void testFindRealRoots() {
```
Comment (stefanhahmann) [inline src/test/java/org/mastodon/util/TreeUtilsTest.java:80]: The name of this test still reflects the old method name. Do you want to keep this name anyway or do you want to consider to refactor to testFindRootsOfTheGivenNodes()?

**Review by stefanhahmann — CHANGES_REQUESTED** [review]

File: src/test/java/org/mastodon/util/TreeUtilsTest.java (hunk 13 above)
Comment (maarzt) [reply src/test/java/org/mastodon/util/TreeUtilsTest.java]: I updated the name of the method as suggested.

File: src/main/java/org/mastodon/util/TreeUtils.java
Comment (tinevez) [reply src/main/java/org/mastodon/util/TreeUtils.java:1]: Yes exactly. Do you think it is a good fit? One fewer class.... that would be nice.

File: src/main/java/org/mastodon/util/TreeUtils.java (hunk 9 above)
Comment (stefanhahmann) [reply src/main/java/org/mastodon/util/TreeUtils.java]: Okay. You can mark this comment as resolved.

**Review by stefanhahmann — APPROVED** [review]
I approve this PR
